apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mavenstset
spec:
  selector:
    matchLabels:
      app: mavenstsetapp
  serviceName: mavenstsetsvc
  replicas: 1
  template:
    metadata:
      labels:
        app: mavenstsetapp
    spec:
      containers:
      - name: mavenstsetapp
        image: maven:3.6.3-openjdk-8-slim
        #image: openjdk:11-slim-buster
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        command: ["/bin/bash", "-c", "sleep infinity"]